AT_CRUD/Models/Amigo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AT_CRUD.Models
{
    public class Amigo
    {
        public int AmigoId { get; set; }

        public string Nome { get; set; }

        public string SobreNome { get; set; }


        public int Idade { get; set; }

        public DateTime Aniversario { get; set; }
    }
}

AT_CRUD/Models/AniversarianteViewModel.cs
using System.Collections.Generic;

namespace AT_CRUD.Models
{
    public class AniversarianteViewModel
    {
        public IEnumerable<Models.Amigo> Aniversariantes { get; set; }

        public IEnumerable<Models.Amigo> ProximosAniversariantes { get; set; }
    }
}

AT_CRUD/Models/ErrorViewModel.cs
using System;

namespace AT_CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AT_CRUD/Controllers/AmigosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AT_CRUD.Data;
using AT_CRUD.Models;

namespace AT_CRUD.Controllers
{
    public class AmigosController : Controller
    {
        private readonly AT_CRUDContext _context;

        public AmigosController(AT_CRUDContext context)
        {
            _context = context;
        }

        // GET: Amigoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Amigo.ToListAsync());

        }

        [HttpPost]

        public async Task<IActionResult> Index(string nome)
        {
            var dados = await _context.Amigo.Where(a => a.Nome == nome).ToListAsync();

            return View("Index", dados);
        }

        // GET: Amigoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo
                .FirstOrDefaultAsync(m => m.AmigoId == id);
            if (amigo == null)
            {
                return NotFound();
            }

            return View(amigo);
        }

        // GET: Amigoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Amigoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AmigoId,Nome,SobreNome,Idade,Aniversario")] Amigo amigo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(amigo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(amigo);
        }

        // GET: Amigoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo.FindAsync(id);
            if (amigo == null)
            {
                return NotFound();
            }
            return View(amigo);
        }

        // POST: Amigoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AmigoId,Nome,SobreNome,Idade,Aniversario")] Amigo amigo)
        {
            if (id != amigo.AmigoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(amigo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AmigoExists(amigo.AmigoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(amigo);
        }

        // GET: Amigoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var amigo = await _context.Amigo
                .FirstOrDefaultAsync(m => m.AmigoId == id);
            if (amigo == null)
            {
                return NotFound();
            }

            return View(amigo);
        }

        // POST: Amigoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var amigo = await _context.Amigo.FindAsync(id);
            _context.Amigo.Remove(amigo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AmigoExists(int id)
        {
            return _context.Amigo.Any(e => e.AmigoId == id);
        }
    }
}

AT_CRUD/Controllers/HomeController.cs
using AT_CRUD.Data;
using AT_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AT_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly AT_CRUDContext _context;

        

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, AT_CRUDContext context)
        {
            _logger = logger;
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var aniversariantes = await _context.Amigo
                .Where(a => a.Aniversario.AddYears(DateTime.Now.Year - a.Aniversario.Year) >= DateTime.Now.Date &&
                        a.Aniversario.AddYears(DateTime.Now.Year - a.Aniversario.Year) <= DateTime.Now.Date.AddDays(1))
                .ToListAsync();

            var proxaniversarios = await _context.Amigo.Where(a => a.Aniversario.AddYears(DateTime.Now.Year - a.Aniversario.Year) >= DateTime.Now.Date &&
                        a.Aniversario.AddYears(DateTime.Now.Year - a.Aniversario.Year) <= DateTime.Now.Date.AddMonths(1))
                .ToListAsync();


            return View(new AniversarianteViewModel 
            { 
                Aniversariantes = aniversariantes, ProximosAniversariantes = proxaniversarios 
            });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AT_CRUD/Views/Amigos/Create.cshtml
@model AT_CRUD.Models.Amigo

@{
    ViewData["Title"] = "Create";
}

<h1>Adicionar Amigo na Lista</h1>
<!--<style scoped>
    div {
        background-color: whitesmoke;
    }
</style> -->

<h4>Amigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SobreNome" class="control-label"></label>
                <input asp-for="SobreNome" class="form-control" />
                <span asp-validation-for="SobreNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input type="date" asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_CRUD/Views/Amigos/Delete.cshtml
@model AT_CRUD.Models.Amigo

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar Amigo</h1>

<h3>Tem certeza que irá deletar?</h3>
<div>
    <h4>Amigo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SobreNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aniversario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aniversario)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AmigoId" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para Lista</a>
    </form>
</div>

AT_CRUD/Views/Amigos/Details.cshtml
@model AT_CRUD.Models.Amigo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes de Amigo <img src="~/Assets/Img/file-person.svg" class="img" width="35" alt="Amigo" /></h1>

<div>
    <h4>Principais informações:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SobreNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aniversario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aniversario)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AmigoId">Editar <img src="~/Assets/Img/pencil.svg" class="img" fill="currentColor" alt="Editar" /></a> |
    <a asp-action="Index">Voltar para a Lista</a>
</div>

AT_CRUD/Views/Amigos/Edit.cshtml
@model AT_CRUD.Models.Amigo

@{
    ViewData["Title"] = "Edit";
}

<h1>Página de Editão do Amigo</h1>

<h4>Amigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AmigoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SobreNome" class="control-label"></label>
                <input asp-for="SobreNome" class="form-control" />
                <span asp-validation-for="SobreNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input type="date" asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_CRUD/Views/Amigos/Index.cshtml
@model IEnumerable<AT_CRUD.Models.Amigo>

@{
    ViewData["Title"] = "Lista";
}


<h1>Lista de Amigos</h1>

<p>
    <a class="buttonAdd" asp-action="Create"> Adicionar Amigo <img src="~/Assets/Img/check-circle-fill.svg" class="img" fill="currentColor" alt="Adicionar Amigo" /> </a>
</p>

<div class="col-4 p-0 justify-content-end">
    <form asp-controller="Amigos" asp-action="Index">
        <input class="btn-group" type="text" name="nome" />
        <span type="text" placeholder="Nome do Amigo">
            <input class="btn-sm btn-info" type="submit" value="Filtrar" />
        </span>

    </form>
    <div>
        <a asp-action="Index">Limpar Filtro</a>
    </div>

</div>

<table class="table">
    <thead>
        <tr>
            <th>
                <h7>ID/SKU</h7>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SobreNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aniversario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AmigoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aniversario)
            </td>
            <td>
                <a asp-action="Edit" class="buttonEdit" asp-route-id="@item.AmigoId">Editar <img src="~/Assets/Img/pencil.svg" class="img" fill="currentColor" alt="Editar" /></a> |
                <a asp-action="Details" class="buttonInfo" asp-route-id="@item.AmigoId">Detalhes <img src="~/Assets/Img/info-circle.svg" class="img" fill="currentColor" alt="Informações" /></a> |
                <a asp-action="Delete" class="buttonErase" asp-route-id="@item.AmigoId">Deletar <img src="~/Assets/Img/eraser-fill.svg" class="img" fill="currentColor" alt="Deletar" /></a>
            </td>
        </tr>
}
    </tbody>
</table>

AT_CRUD/Views/Home/Index.cshtml
@model AT_CRUD.Models.AniversarianteViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2>Bem-vindo</h2>
    <h1 class="display-4">CRUD - Cadastro de Amigos</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

</div>
<div class="align-content-lg-between">
    <div class="text-center">
        <p>🎂 Aniversariante do dia 🎂</p>
        <p>##</p>
        <table class="table">
            @foreach (var item in Model.Aniversariantes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SobreNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aniversario)
                    </td>
                    <td>
                </tr>
            }
        </table>
        <hr />
        <p>Próximos aniversariantes:</p>

        <table class="table">
            @foreach (var item in Model.ProximosAniversariantes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SobreNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aniversario)
                    </td>
                    <td>
                </tr>
            }
        </table>

    </div>
</div>

AT_CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AT_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style scoped>
        div {
            background-color: whitesmoke;
        }

        nav {
            background-color: whitesmoke;
        }

        a {
            list-style: none;
            transition: 0.3s opacity;
            text-decoration: none;
        }

            a:hover {
                opacity: 0.7;
                color: #000000;
                text-decoration: none;
            }
        .buttonAdd {
            border: 3px solid #04AA6D;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonErase {
            border: 3px solid #ff5050;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonEdit {
            border: 3px solid #ffd452;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonInfo {
            border: 3px solid #52d4ff;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AT_CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Amigos" asp-action="Index">Lista de Amigos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AT_CRUD - Feito por Eric F Guimarães - <a href="https://linkedin.com/in/ericfguimaraes"><img src="~/Assets/Img/linkedin.svg" class="img" width="20" alt="Linkedin"/></a> | 
            <a href="https://github.com/ericfg19/"><img src="~/Assets/Img/github.svg" class="img" width="22" alt="GitHub" /></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>